volumes:
  providers:
    driver: local
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:9.6
    container_name: tp-keycloak-pg
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 6543:5432

  providers:
    image: alpine:3.20.3
    command: [
      "/bin/sh",
      "-c",
      "apk add ca-certificates && update-ca-certificates && rm -f /providers/* && cp /local/admin.jar /providers && wget -O /providers/keycloak-home-idp-discovery.jar https://github.com/tidepool-org/keycloak-home-idp-discovery/releases/download/v26.1.1/keycloak-home-idp-discovery.jar"]
    volumes:
      - ./admin/target/admin-LATEST.jar:/local/admin.jar
      - providers:/providers

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: tp-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      TIDEPOOL_APP_URL: "https://app.tidepool.org"
      TIDEPOOL_ASSETS_URL: "https://s3-us-west-2.amazonaws.com/tidepool-qa1-asset"
      TIDEPOOL_ZENDESK_KEY: "d1aad8b3-67d8-4f44-9d87-9e8a0ed8149d"
    ports:
      - 8089:8080
    volumes:
      - ./tidepool-theme:/opt/keycloak/themes/tidepool
      - providers:/opt/keycloak/providers
    depends_on:
      providers:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    command: start-dev
